package com.lennart.model;

import java.util.*;

/**
 * Created by LennartMac on 18/11/2020.
 */
public class InstaAccounts {

    public List<String> getAllInstaAccounts() {
        List<String> users = new ArrayList<>();

        users.add("adalla.99");
        users.add("aichaverheye");
        users.add("allaboutmaerry");
        users.add("amaka.hamelijnck");
        users.add("amberdhaan");
        users.add("ambermeiresonne");
        users.add("ambervanasbroeck");
        users.add("amberweyn");
        users.add("amelie_weissenberger");
        users.add("ana_elisa_");
        users.add("angelajakaj");
        users.add("angelastolemyname");
        users.add("angelllllllllllllllll");
        users.add("ankatrien");
        users.add("annabelpesant");
        users.add("annanooshin");
        users.add("anneepedersen");
        users.add("annelise_ho");
        users.add("anthonisevelien");
        users.add("asmolenaarr");
        users.add("aukjebergman");
        users.add("axelledorel_");
        users.add("azukanl");
        users.add("beautygloss");
        users.add("bente.visser");
        users.add("betipierce");
        users.add("betuel.klkn");
        users.add("bibibreijman");
        users.add("bibikleinenberg");
        users.add("bomink_");
        users.add("bonitabodden");
        users.add("bowilkes");
        users.add("bridgetmaasland");
        users.add("brigi_bla");
        users.add("brittmink_");
        users.add("brittwijnne");
        users.add("broganwest");
        users.add("by.rachellx");
        users.add("campbellblairr");
        users.add("carolienmichel");
        users.add("carolienspoor");
        users.add("carrieslifestyle");
        users.add("cassndras");
        users.add("celinedekkerr");
        users.add("chameebarkmanx");
        users.add("channahkoerten");
        users.add("chantbaltes");
        users.add("charlotte_westlund");
        users.add("charlottejanssen94");
        users.add("chloevandenbussche");
        users.add("chlojl_");
        users.add("clairepronk");
        users.add("claudinebuisman");
        users.add("cocochloe__");
        users.add("coraliedelmarcelle");
        users.add("countlessshades");
        users.add("crdr.samira");
        users.add("cwrekenhorst");
        users.add("cynthiavandoorn");
        users.add("daelostylo");
        users.add("dananygaardnielsen");
        users.add("daniquehogguer");
        users.add("danthescholtenx");
        users.add("daphnesonneveld");
        users.add("daphnevanbuerink");
        users.add("dayenneritchi");
        users.add("debbiedhillon");
        users.add("dee");
        users.add("dehuismuts");
        users.add("deminugteren");
        users.add("demirenee.officiall");
        users.add("demiteeuwissen");
        users.add("demivthuil");
        users.add("deveganmoeder");
        users.add("dewipijnacker");
        users.add("dianegroenhof");
        users.add("diesnaloomans");
        users.add("diliane.kwadijk");
        users.add("djwef");
        users.add("dominiquekaylee");
        users.add("eef_dgn");
        users.add("elenawarners");
        users.add("eliencatteeuw");
        users.add("elina.pltv");
        users.add("elinevdlinde");
        users.add("elise.bak");
        users.add("eliseboers");
        users.add("emilie.terloo");
        users.add("emiliegharbi");
        users.add("emiliejbekken");
        users.add("emilypeeraer");
        users.add("emmagardeslen");
        users.add("esmeedekorte");
        users.add("esmeevanleijden");
        users.add("evaofficialnl");
        users.add("ewancosh");
        users.add("fabiennedavelaar");
        users.add("fabiennemeilanie");
        users.add("fallon.fashionn");
        users.add("fashionkittenandlawyer");
        users.add("fayaofficial");
        users.add("felicia.louhenapessy");
        users.add("femke.vermaas");
        users.add("femkezoe");
        users.add("fitwithmarit");
        users.add("fleurdijkstra_");
        users.add("fleurmaas_");
        users.add("fleurnijbacker");
        users.add("fleurwesthoek");
        users.add("florinecmh");
        users.add("ginasingels");
        users.add("ginn.xo");
        users.add("ginneynoa");
        users.add("guusjewm");
        users.add("hannah.arguelles");
        users.add("indiasuy");
        users.add("inspiredbyyam");
        users.add("irisamber");
        users.add("iriseigenhuis");
        users.add("irisenthoven");
        users.add("iriskristen");
        users.add("irismarkerink");
        users.add("iriszeilstra");
        users.add("isaluna");
        users.add("itizyana");
        users.add("itsaboutellly");
        users.add("itsjusttix");
        users.add("jadeanna");
        users.add("jaimyruys");
        users.add("janelle_framery");
        users.add("janinedebart");
        users.add("jasmijnkremer");
        users.add("jel_nl");
        users.add("jenehknoopp");
        users.add("jessicakuijpers");
        users.add("jessiejazzvuijk");
        users.add("jillangell");
        users.add("jippheldoorn");
        users.add("jolielot");
        users.add("jonievis");
        users.add("joshveldhuizen");
        users.add("julia_opett");
        users.add("juliacatharinax");
        users.add("juliajohannadebruin");
        users.add("juliavanbergen");
        users.add("juliavkatwijk");
        users.add("julie.vangoids");
        users.add("julieplnn");
        users.add("julievandooren");
        users.add("junoordzij");
        users.add("justinevanruymbeke");
        users.add("juultjetieleman");
        users.add("kaat_hermans");
        users.add("kaesutherland");
        users.add("kamilasara_k");
        users.add("karivdheide");
        users.add("kathys.lookbook");
        users.add("katjaschuurman");
        users.add("kelly.van.rossum");
        users.add("kellybeukers");
        users.add("kellycaresse");
        users.add("kellyhamelijnck");
        users.add("ketabaia__");
        users.add("kheeell");
        users.add("kim.musk");
        users.add("kimandthekids");
        users.add("kimberlybrands_");
        users.add("kimjacobs");
        users.add("kimkotter");
        users.add("kimlianvdmeij");
        users.add("kimvanwinkelhof");
        users.add("krissiklr");
        users.add("kusbianca");
        users.add("kuss.pas");
        users.add("kyra.vaneck");
        users.add("kyrajanssenn");
        users.add("lamynaspinder");
        users.add("larissaselene");
        users.add("laurahordijk_");
        users.add("lauraponticorvo");
        users.add("lauravdee");
        users.add("lauraxdams");
        users.add("laviesanne");
        users.add("laylaeyers");
        users.add("leonacathrina");
        users.add("leslie_keijzer");
        users.add("liafailwijnen");
        users.add("liefselyse");
        users.add("liefslotte");
        users.add("liefthuis");
        users.add("lies_zhara");
        users.add("liisavde");
        users.add("lindsaywouterse");
        users.add("lindseybeljaars");
        users.add("lindsy_tips");
        users.add("linnndademunck");
        users.add("lisaapijnacker");
        users.add("lisadamenv");
        users.add("lisagoesvegan");
        users.add("lisahoogendoorn");
        users.add("lisajkoster");
        users.add("lisanne.blonk");
        users.add("lisannekoning");
        users.add("lisvanderwijst");
        users.add("lizetgreve");
        users.add("lizzyvdligt");
        users.add("loisblog");
        users.add("lolannaa");
        users.add("lotte.ngm");
        users.add("louisasth");
        users.add("louise_compier");
        users.add("louisevandermeijs");
        users.add("lterveld");
        users.add("luna.hapers");
        users.add("lunaweerman");
        users.add("luucy.schmidt");
        users.add("m7mmichelle");
        users.add("macyymichelle");
        users.add("madame.vio");
        users.add("madelonhaantjes");
        users.add("maikebeunk");
        users.add("maitedk");
        users.add("manondelang");
        users.add("mariatailor");
        users.add("marielledouwsma_");
        users.add("marieyou__");
        users.add("marijezuurveld");
        users.add("mariska.van.es");
        users.add("maritkramer_");
        users.add("marleen.hekkert");
        users.add("marlie_xx");
        users.add("marlyhartje");
        users.add("marlyvd");
        users.add("martaswiggers");
        users.add("martinemaureen");
        users.add("mascha.danique");
        users.add("maximemeiland");
        users.add("mayridts");
        users.add("medinaletica");
        users.add("melissa_nh");
        users.add("melissa_poli");
        users.add("melissavijgen");
        users.add("melsssz_");
        users.add("merel.christina");
        users.add("merleamanda");
        users.add("michelle_bollen");
        users.add("michellefleur");
        users.add("michellelouwaars");
        users.add("michellemiddelman");
        users.add("michelleterlinden");
        users.add("michellevsm_");
        users.add("miespiration");
        users.add("miraennen");
        users.add("moderosaofficial");
        users.add("momofalyadua");
        users.add("mona_lchtnbrg");
        users.add("monicageuze");
        users.add("moniquesmit_insta");
        users.add("mrsjamieli");
        users.add("mrskeizer");
        users.add("mrspinay");
        users.add("mzlanie");
        users.add("naadines");
        users.add("naomivaneeren_");
        users.add("natalievijfhuizen");
        users.add("nataschalike");
        users.add("nathalieejw");
        users.add("nenciesway");
        users.add("nienkebakker");
        users.add("ninaa_mk");
        users.add("ninahouston");
        users.add("ninalaurent_");
        users.add("ninaschotpoort");
        users.add("ninawarink");
        users.add("nisavanbaelen");
        users.add("nochtlii");
        users.add("nonstopnikki.nl");
        users.add("noordegroot");
        users.add("noortje.smit");
        users.add("nova__vv");
        users.add("nynkecamps");
        users.add("olcay");
        users.add("patricia_paay");
        users.add("paulienmullaertx");
        users.add("paulinakurka");
        users.add("paulinedebaere");
        users.add("paulinepain_");
        users.add("positivemeryem");
        users.add("quincyheemskerk");
        users.add("r.eginab");
        users.add("rebeccavandenhoek");
        users.add("remke");
        users.add("reneenatassja");
        users.add("rentishehu");
        users.add("rianne.meijer");
        users.add("rijneker_rebels");
        users.add("rmdnbs");
        users.add("robinhenneke.jpeg");
        users.add("rochellehondijk");
        users.add("romeescholtenx");
        users.add("rosalia_guzman_9");
        users.add("saarkoningsberger");
        users.add("sabrinaputrix");
        users.add("salezusjes");
        users.add("sanneghislaine");
        users.add("sara.westerman");
        users.add("sarah.dmry");
        users.add("sarahliebregts");
        users.add("sarahrebeccanl");
        users.add("saskiaweerstand");
        users.add("serenaverbon");
        users.add("shannblogtnl");
        users.add("sharanibaskaran");
        users.add("sharonvdw__");
        users.add("shelcycarpentier");
        users.add("shellysterk");
        users.add("shirleyvisser");
        users.add("shularoose");
        users.add("silke.carpentier");
        users.add("sim.bae");
        users.add("sofiegraafland");
        users.add("sonamammadova");
        users.add("sophiemilzink");
        users.add("sophieousri");
        users.add("staceeyyx");
        users.add("stephaniematthijs");
        users.add("stijn_fransen");
        users.add("susangorz_");
        users.add("suuslothmann");
        users.add("sylvana.elling");
        users.add("t.a.creatives");
        users.add("taraverbon");
        users.add("tessveldkampx");
        users.add("thehayleyanne");
        users.add("thepastelsuitcase");
        users.add("tiaravanessaa");
        users.add("tienvanwil");
        users.add("tinason__");
        users.add("tudaumeko1");
        users.add("valeriequinta");
        users.add("valeriequirijns");
        users.add("valeryriemens");
        users.add("veerlejodieke");
        users.add("veradokter");
        users.add("vidanaaaa");
        users.add("virginiavdbeek");
        users.add("vita.cleo");
        users.add("washed_out_denim");
        users.add("watikvandaagweet");
        users.add("wendievlaar");
        users.add("wilvantien");
        users.add("x.x.emma.xx");
        users.add("xdemi___x");
        users.add("xisabel.kr");
        users.add("xmylifeasayla");
        users.add("xnoarichter");
        users.add("xpeterinabroers");
        users.add("xsam_xm");
        users.add("xshirleyp");
        users.add("yelda.cskn");
        users.add("yung.demi");
        users.add("zoeoerlemans");
        users.add("zoeppn_");

        return users;
    }

    //not to use
    //allaboutmaerry
    //kathys.lookbook
    //lolannaa
    //momofalyadua
    //mona_lchtnbrg
    //kleinermilchbart
    //sarah.dmry
    //tiaravanessaa

    //mayb wel:
    //floordehaann
    //gewoonnanoek
    //mereldewildeman
    //fannybgn
    //siljekristiansen
    //celiabrl
    //may_cate
    //betulakbaba

    //a.nnickk_
    //tanjakvl

    //geraldine_kemper

    //chiaracappellano

    //reneehemmes
}
